[general]
# if this path is encountered during path traversal,
# it will be removed. this is useful for instances
# where your absolute domain path is not long enough
# to replace boomlings.com, because you can then point
# it at a different, longer path to fill the gap
#
# example:
#   boomlings.com/database/
#   example.com/aaaaaaaaaa/
#               ^^^^^^^^^^^
# leaving as empty will disable this
append_path = ""
# where can your server be accessible?
port = 8000
[accounts]
# allow new accounts to be created
allow_registration = true

[db]
# path for your data to be stored
data_folder = "data"

[levels]
# max amount of objects in a level
max_objects = 80_000
# object ids to block
blocklist = [ 31 ] # start position
# if reuploading levels is allowed
reupload = true